### ISSUE TITLE
Is there discord channel?

### ISSUE THREAD

**Issue by portlek** [okyanus-mc/meta#2]

**Comment by Admicos** [comment]
Not at the moment, no. However, I was planning to make one soon. Do you think it's neccesary?

**Comment by portlek** [comment]
no it's not neccesary for now, maybe after the first release

**Comment by Admicos** [comment]
We're already at 0.2.0 :p

But then it happened real fast, so you might not've been aware.

**Comment by portlek** [comment]
no actually 1.0.0 release, not pre-release

**Comment by Admicos** [comment]
Ah, that makes sense. Still, I feel like it could be helpful for real time communication. And questions, maybe.
